### ISSUE TITLE
buggy label when adding a passwort with "gopass create"

### ISSUE THREAD

**Issue by danielKugler** [codecentric/gopass-ui#29]
When I create a new store item with
$ gopass create

the label with the passwort shows something like this:
m.y.s.e.c.r.e.t.p.a.s.s.w.d.comment: url: github.comusername: my@email.com

**Comment by ruettenm** [comment]
Hi @danielKugler, could you provide a screenshot to see the issue? This sounds really curious 🤔

**Comment by danielKugler** [comment]
I uploaded an image of the UI here:
[https://pasteboard.co/IEvRXfi.png](https://pasteboard.co/IEvRXfi.png)

**Comment by rngtng** [comment]
same issue here..

**Comment by jverhoelen** [comment]
Hey @danielKugler & @rngtng 
the reason for this behaviour is simple. The wizard-guided "gopass create" creates secrets with a formatted value (because in addition to the secret value itself also other fields are stored) in YAML.

At the very beginning Gopass UI was built on the simple premise that the secrets' value is only a simple string, not containing additional fields.

This is similar to #28 ("multiline secret").
I will assign myself and implement multiline functionality, hopefully within the next few weeks.

**Comment by jverhoelen** [comment]
Multiline secret handling was now implemented and merged into master (#33). It will be included in the next release which will be published within the next days or weeks.
