### ISSUE TITLE
Missing deb asset in v0.6.0

### ISSUE THREAD

**Issue by abacao** [codecentric/gopass-ui#44]
Hello all,

the latest version doesn't have a deb file.

Can you please provide that?

**Comment by jverhoelen** [comment]
Sorry for missing out on the Debian asset in our last release. I think we will have a new release very soon. I will take care to build the deb asset again. Had some problems during the last build and decided to skip solving the problem due to time limitations.

I will keep this issue open until you've been provided with the correct release 😉

**Comment by abacao** [comment]
@jverhoelen Awesome.
Can I make a suggestion: please create a tutorial/explanation on how to build a deb from source (example).
This way, in case of missing something, users can build the deb themselves (and maybe contribute with some kind of universal package like snaps)

**Comment by jverhoelen** [comment]
Hey @abacao,
Gopass 0.7.0 is out now with a deb release again, feel free to grab it: https://github.com/codecentric/gopass-ui/releases/tag/v0.7.0

I extended the [releasing documentations](https://github.com/codecentric/gopass-ui/blob/master/docs/releasing.md) and [documentations about supported platforms](https://github.com/codecentric/gopass-ui/blob/master/docs/platforms-and-packages.md). TL;DR: binaries for all platforms can be built using `npm run release:full`.

I hope that helps, but should not be required as of the new release 😃
