### ISSUE TITLE
issue gopass is not saving new passsword when editing it

### ISSUE THREAD

**Issue by dummys** [codecentric/gopass-ui#72]
when clicking save, nothing happend. Tried to click many time, same problem.
when clicking quit, nothing is changed.

**Comment by ruettenm** [comment]
Hi, thanks for reporting the issue. Which gopass version are you using?

**Comment by dummys** [comment]
-> $ gopass -v
gopass 1.10.1 (2020-09-13 00:16:24) go1.15.2 linux amd64

**Comment by isodude** [comment]
I think the problem is here
https://github.com/codecentric/gopass-ui/blob/a1949e21d0c95725b1e5cdbc28221c17a9e508ff/src/renderer/explorer-app/pages/details/SecretDetailsPage.tsx#L77

which is using
https://github.com/codecentric/gopass-ui/blob/8009a50642fc49fbb4aca2a2bb4b81b6d2c792ab/src/renderer/secrets/Gopass.ts#L111

Gopass does not allow an insert on an existing entry
https://github.com/gopasspw/gopass/blob/08b7d56d65bdd3745ff500a2e0921596131b6713/internal/action/insert.go#L61

So I see a two options
* set force flag when inserting
* use append only
* use append when only new lines are changed and force if else

**Comment by dummys** [comment]
thanks guy :D
