### ISSUE TITLE
Global search window doesn't appear

### ISSUE THREAD

**Issue by lockejan** [codecentric/gopass-ui#82]
Hello,
when triggering the global search window I only face a white pane.
It is not reacting to any kind of input except closing it with cmd+w.
This seems broken to me.

I'm using:
- macOs 11.4
- gopass-ui 0.8.0
- gopass 1.12.7
- gpg 2.3.1

**Comment by lockejan** [comment]
After a OS restart this error message appeared (see screenshot). Closing and restarting gopass-ui resulted in the aforementioned behaviour.

![image](https://user-images.githubusercontent.com/25434434/124910121-849b2200-dfeb-11eb-9874-15dfc88ac34c.png)

**Comment by jverhoelen** [comment]
Hey @lockejan, you correctly found out that we accidentally broke the global search window in the latest release. I'm very sorry for that. Finally had the time to analyse and fix this.

The fix is included in a re-upload of the [latest release (0.8.0](https://github.com/codecentric/gopass-ui/releases/tag/v0.8.0)) so you should be fine again when downloading and re-installing Gopass UI.

Please let me know if it works after trying that out. Ping me if you face other problems & thanks for reporting this issue!
